import type { CommandNode } from './introspect.js';

function optionTokens(node: CommandNode): string[] {
  const tokens: string[] = [];
  for (const opt of node.options) {
    if (opt.long) tokens.push(opt.long);
    if (opt.short) tokens.push(opt.short);
  }
  return tokens;
}

function collectNodes(node: CommandNode, path: string, out: Map<string, CommandNode>): void {
  out.set(path, node);
  for (const child of node.subcommands) {
    collectNodes(child, `${path} ${child.name}`, out);
  }
}

/**
 * Generates a bash completion script. Intentionally avoids `declare -A`
 * (bash 4+ only) since macOS ships bash 3.2 — the whole thing is
 * case-statements over a plain string "path" variable, which works on
 * both bash 3.2 and modern bash.
 */
export function generateBashCompletion(root: CommandNode): string {
  const nodes = new Map<string, CommandNode>();
  collectNodes(root, root.name, nodes);

  const pathDetectionCases: string[] = [];
  const offerCases: string[] = [];

  for (const [path, node] of nodes) {
    if (node.subcommands.length > 0) {
      const childNames = node.subcommands.map((c) => c.name).join('|');
      pathDetectionCases.push(
        `      "${path}") case "$w" in\n          ${childNames}) path="$path $w" ;;\n        esac ;;`
      );
    }
    const subNames = node.subcommands.map((c) => c.name).join(' ');
    const opts = optionTokens(node).join(' ');
    offerCases.push(`    "${path}") subcommands="${subNames}"; options="${opts}" ;;`);
  }

  return `#!/usr/bin/env bash
# dova shell completion for bash — generated by \`dova completion bash\`.
# Install by sourcing it, e.g.: source <(dova completion bash)
# or write it to your bash-completion.d directory.

_${root.name}_completions() {
  local cur path w i
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  path="${root.name}"

  for (( i=1; i<COMP_CWORD; i++ )); do
    w="\${COMP_WORDS[i]}"
    if [[ "$w" != -* ]]; then
      case "$path" in
${pathDetectionCases.join('\n')}
      esac
    fi
  done

  local subcommands="" options=""
  case "$path" in
${offerCases.join('\n')}
  esac

  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$options" -- "$cur") )
  else
    COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
  fi
}

complete -F _${root.name}_completions ${root.name}
`;
}
