import type { CommandNode } from './introspect.js';

function escapeSingleQuotes(s: string): string {
  return s.replace(/'/g, "\\'");
}

/**
 * fish completions are declarative `complete` lines gated by
 * `__fish_seen_subcommand_from`. fish matches subcommand tokens anywhere
 * on the line (not strict position), so each node's condition is "have
 * seen every ancestor, and not yet seen one of my own children" — good
 * enough fidelity for a tree this shallow, and it's the standard fish
 * idiom (real fish completions for git etc. use exactly this pattern).
 */
export function generateFishCompletion(root: CommandNode): string {
  const lines: string[] = [
    `# dova shell completion for fish — generated by \`dova completion fish\`.`,
    `# Install: dova completion fish > ~/.config/fish/completions/${root.name}.fish`,
    '',
    `complete -c ${root.name} -f`,
    '',
  ];

  function walk(node: CommandNode, ancestors: string[]): void {
    const seenAncestors = ancestors.map((a) => `__fish_seen_subcommand_from ${a}`);

    if (node.subcommands.length > 0) {
      const childNames = node.subcommands.map((c) => c.name);
      const conditionParts = [...seenAncestors, `not __fish_seen_subcommand_from ${childNames.join(' ')}`];
      const condition = conditionParts.join('; and ');
      for (const child of node.subcommands) {
        lines.push(
          `complete -c ${root.name} -n '${condition}' -a '${child.name}' -d '${escapeSingleQuotes(child.description)}'`
        );
      }
    }

    if (node.options.length > 0) {
      const condition = seenAncestors.length > 0 ? seenAncestors.join('; and ') : 'true';
      for (const opt of node.options) {
        const parts = [`complete -c ${root.name} -n '${condition}'`];
        if (opt.short) parts.push(`-s ${opt.short.replace(/^-/, '')}`);
        if (opt.long) parts.push(`-l ${opt.long.replace(/^--/, '')}`);
        parts.push(`-d '${escapeSingleQuotes(opt.description)}'`);
        lines.push(parts.join(' '));
      }
    }

    for (const child of node.subcommands) {
      walk(child, [...ancestors, child.name]);
    }
  }

  walk(root, []);
  return `${lines.join('\n')}\n`;
}
