import type { CommandNode } from './introspect.js';

function psString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function psStringArray(values: string[]): string {
  return `@(${values.map(psString).join(', ')})`;
}

/** Serializes a CommandNode into a PowerShell nested-hashtable literal. */
function serializeNode(node: CommandNode, indent: string): string {
  const options = [...node.options.map((o) => o.long).filter((v): v is string => Boolean(v)), ...node.options.map((o) => o.short).filter((v): v is string => Boolean(v))];
  const childIndent = `${indent}    `;
  const subcommandsBlock =
    node.subcommands.length === 0
      ? '@()'
      : `@(\n${childIndent}    ${node.subcommands.map((c) => serializeNode(c, childIndent)).join(`\n${childIndent}    `)}\n${childIndent})`;
  return `@{
${childIndent}name = ${psString(node.name)}
${childIndent}options = ${psStringArray(options)}
${childIndent}subcommands = ${subcommandsBlock}
${indent}}`;
}

/**
 * PowerShell completion via `Register-ArgumentCompleter -Native`. Unlike
 * the bash/zsh/fish generators (one branch of logic per path), the whole
 * command tree is serialized as a nested hashtable and one generic script
 * block walks it at completion time — same tree, same idea, just native
 * PowerShell data instead of shell case-statements.
 */
export function generatePowerShellCompletion(root: CommandNode): string {
  const tree = serializeNode(root, '');

  return `# dova shell completion for PowerShell — generated by \`dova completion powershell\`.
# Install: dova completion powershell >> $PROFILE

$__${root.name}CompletionTree = ${tree}

Register-ArgumentCompleter -Native -CommandName ${root.name} -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = $commandAst.CommandElements | ForEach-Object { $_.ToString() } | Select-Object -Skip 1
    $node = $__${root.name}CompletionTree

    foreach ($t in $tokens) {
        if ($t -eq $wordToComplete) { continue }
        $next = $node.subcommands | Where-Object { $_.name -eq $t }
        if ($next) { $node = $next }
    }

    if ($wordToComplete -like '-*') {
        $candidates = $node.options
    } else {
        $candidates = $node.subcommands | ForEach-Object { $_.name }
    }

    $candidates | Where-Object { $_ -like "$wordToComplete*" } | Sort-Object | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
}
`;
}
