import type { CommandNode } from './introspect.js';
import { generateBashCompletion } from './bash.js';

/**
 * zsh completion, via zsh's own `bashcompinit` shim rather than a
 * hand-rolled `_arguments`/`_describe` implementation: it's the same
 * generated logic as bash's, so there is exactly one code path (bash.ts)
 * generating the tree-walking logic for both shells.
 */
export function generateZshCompletion(root: CommandNode): string {
  const bash = generateBashCompletion(root);
  return `#compdef ${root.name}
# dova shell completion for zsh — generated by \`dova completion zsh\`.
# Install by sourcing it, e.g.: source <(dova completion zsh)

autoload -U +X compinit && compinit -C
autoload -U +X bashcompinit && bashcompinit

${bash}
`;
}
