import path from 'node:path';
import fs from 'node:fs';
import instructionsBlock from '../agents/instructions.md';

/* ------------------------------------------------------------------ *
 * `dova agents init` — writes dova's usage rules into the files coding
 * agents actually read.
 *
 * Two files, not one, because no single file is read by default by both
 * targets: Windsurf reads a root AGENTS.md always-on (it replaced
 * .windsurfrules as the maintained convention), while VS Code's
 * AGENTS.md support is experimental and off behind `chat.useAgentsMdFile`
 * — there, `.github/copilot-instructions.md` is what works out of the
 * box. The same content goes in both, generated from one source rather
 * than maintained twice.
 *
 * Deliberately not a symlink: a Windows checkout with
 * core.symlinks=false turns one into a text file containing a path,
 * silently, and Azure DevOps shops skew Windows.
 * ------------------------------------------------------------------ */

export const BLOCK_START = '<!-- dova:start -->';
export const BLOCK_END = '<!-- dova:end -->';

const BLOCK_NOTE = `${BLOCK_START}\n<!-- Generated by \`dova agents init\`. Edits inside this block are overwritten; edit outside it freely. -->`;

export interface AgentsTarget {
  /** Repo-relative path. */
  file: string;
  /** Which agent reads it by default, for the summary line. */
  read_by: string;
}

export const TARGETS: AgentsTarget[] = [
  { file: 'AGENTS.md', read_by: 'Windsurf (also Cursor, Devin, Codex)' },
  { file: path.join('.github', 'copilot-instructions.md'), read_by: 'GitHub Copilot in VS Code' },
];

export type BlockAction = 'created' | 'updated' | 'appended' | 'unchanged';

/**
 * Splices dova's block into a file's existing content: replacing it in
 * place if it's already there, appending if the file exists without it,
 * or standing alone in a new file. Everything outside the markers is
 * left exactly as it was — these files usually already say things about
 * the repo that have nothing to do with dova.
 */
export function applyBlock(existing: string | null, block: string): { content: string; action: BlockAction } {
  const wrapped = `${BLOCK_NOTE}\n\n${block.trim()}\n${BLOCK_END}\n`;

  if (existing === null) {
    return { content: wrapped, action: 'created' };
  }

  const start = existing.indexOf(BLOCK_START);
  const end = existing.indexOf(BLOCK_END);
  if (start !== -1 && end !== -1 && end > start) {
    const before = existing.slice(0, start);
    const after = existing.slice(end + BLOCK_END.length).replace(/^\n/, '');
    const content = `${before}${wrapped}${after}`;
    return { content, action: content === existing ? 'unchanged' : 'updated' };
  }

  const separator = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
  return { content: `${existing}${separator}${wrapped}`, action: 'appended' };
}

export interface FileSystemLike {
  readFile(file: string): string | null;
  writeFile(file: string, content: string): void;
  mkdirp(dir: string): void;
}

export const nodeFs: FileSystemLike = {
  readFile: (file) => {
    try {
      return fs.readFileSync(file, 'utf8');
    } catch {
      return null;
    }
  },
  writeFile: (file, content) => fs.writeFileSync(file, content, 'utf8'),
  mkdirp: (dir) => fs.mkdirSync(dir, { recursive: true }),
};

export interface AgentsInstallResult {
  root: string;
  files: Array<{ file: string; read_by: string; action: BlockAction }>;
  warnings: string[];
  dryRun: boolean;
}

/**
 * Copilot honours `.github/copilot-instructions.md` by default, but a
 * `.vscode/settings.json` inherited from a template repo (or an
 * enterprise policy file) can set `useInstructionFiles` to false — in
 * which case everything here is written correctly and silently ignored.
 * Cheap to check, and the alternative is a failure with no symptom.
 */
export function checkCopilotDisabled(fsLike: FileSystemLike, root: string): string | null {
  const settingsPath = path.join(root, '.vscode', 'settings.json');
  const raw = fsLike.readFile(settingsPath);
  if (raw === null) return null;
  // Deliberately a regex rather than JSON.parse: VS Code settings files
  // legitimately contain comments and trailing commas, which JSON.parse
  // rejects — and a parse failure here must not fail the install.
  if (/"github\.copilot\.chat\.codeGeneration\.useInstructionFiles"\s*:\s*false/.test(raw)) {
    return `.vscode/settings.json sets github.copilot.chat.codeGeneration.useInstructionFiles to false — Copilot will ignore .github/copilot-instructions.md until that is true.`;
  }
  return null;
}

export function runAgentsInstall(opts: {
  root: string;
  dryRun?: boolean;
  fs?: FileSystemLike;
  block?: string;
}): AgentsInstallResult {
  const fsLike = opts.fs ?? nodeFs;
  const block = opts.block ?? instructionsBlock;
  const files: AgentsInstallResult['files'] = [];

  for (const target of TARGETS) {
    const absolute = path.join(opts.root, target.file);
    const { content, action } = applyBlock(fsLike.readFile(absolute), block);
    if (!opts.dryRun && action !== 'unchanged') {
      fsLike.mkdirp(path.dirname(absolute));
      fsLike.writeFile(absolute, content);
    }
    files.push({ file: target.file, read_by: target.read_by, action });
  }

  const warnings: string[] = [];
  const copilotWarning = checkCopilotDisabled(fsLike, opts.root);
  if (copilotWarning) warnings.push(copilotWarning);

  return { root: opts.root, files, warnings, dryRun: Boolean(opts.dryRun) };
}
