import path from 'node:path';
import os from 'node:os';
import fs from 'node:fs';
import { UserError } from './errors.js';
import instructionsBlock from '../instructions/block.md';
import skillMd from '../instructions/skill/SKILL.md';
import skillWorkItems from '../instructions/skill/references/work-items.md';
import skillPullRequests from '../instructions/skill/references/pull-requests.md';
import skillAutomation from '../instructions/skill/references/automation.md';
import skillPipelines from '../instructions/skill/references/pipelines.md';

/* ------------------------------------------------------------------ *
 * `dova instructions init` — writes dova's usage rules into the files
 * coding agents actually read.
 *
 * Named for what these files are (VS Code and GitHub both call them
 * "custom instructions") rather than "agents", which now means a custom
 * agent persona — an `.agent.md` role definition with its own tools and
 * model. This command writes neither of those.
 *
 * Two files, not one, because no single file is read by default by both
 * targets. Devin Desktop (what Windsurf became in June 2026; its Cascade
 * agent reached end-of-life that July, replaced by Devin Local) reads a
 * root AGENTS.md as an always-on rule, feeding it into the same rules
 * engine that backs .devin/rules/ — so there's no need to also write
 * .devin/rules/, and the legacy .windsurf/ directory is superseded.
 * VS Code's AGENTS.md support, by contrast, is experimental and off
 * behind `chat.useAgentsMdFile`; there `.github/copilot-instructions.md`
 * is what works out of the box. The same content goes in both,
 * generated from one source rather than maintained twice.
 *
 * Deliberately not a symlink: a Windows checkout with
 * core.symlinks=false turns one into a text file containing a path,
 * silently, and Azure DevOps shops skew Windows.
 * ------------------------------------------------------------------ */

export const BLOCK_START = '<!-- dova:start -->';
export const BLOCK_END = '<!-- dova:end -->';

const BLOCK_NOTE = `${BLOCK_START}\n<!-- Generated by \`dova instructions init\`. Edits inside this block are overwritten; edit outside it freely. -->`;

export interface InstructionsTarget {
  /**
   * Repo-relative path, always forward-slashed. Deliberately not built
   * with path.join: this string is an identity, not a filesystem path —
   * it's what gets printed and put in --json output, and it has to read
   * the same on every platform (path.join would make it
   * `.github\copilot-instructions.md` on Windows). Node accepts forward
   * slashes on Windows, and joining it to an absolute root below
   * normalizes it for the real filesystem anyway.
   */
  file: string;
  /** Which agent reads it by default, for the summary line. */
  read_by: string;
}

export const TARGETS: InstructionsTarget[] = [
  { file: 'AGENTS.md', read_by: 'Devin Desktop / Windsurf (also Cursor, Codex)' },
  { file: '.github/copilot-instructions.md', read_by: 'GitHub Copilot in VS Code' },
];

/**
 * Devin Desktop accepts `agents.md` as well as `AGENTS.md`. On a
 * case-sensitive filesystem, writing the canonical spelling into a repo
 * that already uses the lowercase one would leave two rule files both
 * being read — so an existing variant wins over our preferred casing.
 */
export function resolveAgentsFile(fsLike: FileSystemLike, root: string): string {
  for (const variant of ['AGENTS.md', 'agents.md']) {
    if (fsLike.readFile(path.join(root, variant)) !== null) return variant;
  }
  return 'AGENTS.md';
}

export type BlockAction = 'created' | 'updated' | 'appended' | 'unchanged';

/**
 * Splices dova's block into a file's existing content: replacing it in
 * place if it's already there, appending if the file exists without it,
 * or standing alone in a new file. Everything outside the markers is
 * left exactly as it was — these files usually already say things about
 * the repo that have nothing to do with dova.
 */
export function applyBlock(existing: string | null, block: string): { content: string; action: BlockAction } {
  const wrapped = `${BLOCK_NOTE}\n\n${block.trim()}\n${BLOCK_END}\n`;

  if (existing === null) {
    return { content: wrapped, action: 'created' };
  }

  const start = existing.indexOf(BLOCK_START);
  const end = existing.indexOf(BLOCK_END);
  if (start !== -1 && end !== -1 && end > start) {
    const before = existing.slice(0, start);
    const after = existing.slice(end + BLOCK_END.length).replace(/^\n/, '');
    const content = `${before}${wrapped}${after}`;
    return { content, action: content === existing ? 'unchanged' : 'updated' };
  }

  const separator = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
  return { content: `${existing}${separator}${wrapped}`, action: 'appended' };
}

export interface FileSystemLike {
  readFile(file: string): string | null;
  writeFile(file: string, content: string): void;
  mkdirp(dir: string): void;
  exists(target: string): boolean;
}

export const nodeFs: FileSystemLike = {
  readFile: (file) => {
    try {
      return fs.readFileSync(file, 'utf8');
    } catch {
      return null;
    }
  },
  writeFile: (file, content) => fs.writeFileSync(file, content, 'utf8'),
  mkdirp: (dir) => fs.mkdirSync(dir, { recursive: true }),
  exists: (target) => fs.existsSync(target),
};

/* ------------------------------------------------------------------ *
 * Global install — the default.
 *
 * dova is installed once per machine and works in any repo it's run
 * from, so the rules for using it belong at the same level. A
 * per-repo install (--repo) is for committing them so teammates get
 * them too, which is a different job.
 *
 * One block serves both scopes. Devin's global rules file is capped at
 * 6,000 — half the workspace limit — which the block fits with room to
 * spare, so there is no second, shorter version to keep in step.
 * ------------------------------------------------------------------ */

/** Where each editor keeps its user-level settings, per platform. */
function vscodeUserDirs(home: string): string[] {
  const base =
    process.platform === 'win32'
      ? process.env.APPDATA ?? path.join(home, 'AppData', 'Roaming')
      : process.platform === 'darwin'
        ? path.join(home, 'Library', 'Application Support')
        : path.join(home, '.config');
  return ['Code', 'Code - Insiders', 'VSCodium'].map((variant) => path.join(base, variant, 'User'));
}

export interface ResolvedTarget {
  /** Absolute path written to. */
  path: string;
  /** Shown to the user — home-relative where possible. */
  label: string;
  read_by: string;
  /** Written above the block when the file is created (not on update). */
  preamble?: string;
}

export function resolveGlobalTargets(fsLike: FileSystemLike, home: string): ResolvedTarget[] {
  const targets: ResolvedTarget[] = [
    {
      path: path.join(home, '.codeium', 'windsurf', 'memories', 'global_rules.md'),
      label: '~/.codeium/windsurf/memories/global_rules.md',
      read_by: 'Devin Desktop / Windsurf',
    },
  ];

  // Every VS Code flavour that has actually been run on this machine —
  // writing into one that was never installed just leaves litter.
  const installed = vscodeUserDirs(home).filter((dir) => fsLike.exists(dir));
  const userDirs = installed.length > 0 ? installed : [vscodeUserDirs(home)[0]!];
  for (const dir of userDirs) {
    targets.push({
      path: path.join(dir, 'prompts', 'dova.instructions.md'),
      label: path.join(path.basename(path.dirname(dir)), 'User', 'prompts', 'dova.instructions.md').replace(/\\/g, '/'),
      read_by: 'GitHub Copilot in VS Code (all workspaces)',
      // applyTo is what makes a user-level instructions file apply
      // everywhere rather than to a glob of files.
      preamble: "---\napplyTo: '**'\n---\n",
    });
  }

  return targets;
}

/* ------------------------------------------------------------------ *
 * The skill.
 *
 * The always-on block above has to carry only what must never fail to
 * load — the prohibitions, and which command answers which question.
 * It is capped, and everything that doesn't fit was being cut.
 *
 * Depth goes here instead: full worked scenarios, per-area detail, the
 * behaviour of every flag that matters. SKILL.md stays surface-level
 * and says when to open which reference; hosts show only its name and
 * description until the agent decides it applies, so this costs
 * nothing until it's needed and has no size limit when it is.
 *
 * `.agents/skills/` is the cross-agent location: Devin Desktop reads
 * it and `~/.agents/skills/`, and Copilot reads both plus
 * `~/.copilot/skills/`. One tree serves both editors.
 * ------------------------------------------------------------------ */

export const SKILL_FILES: ReadonlyArray<{ relative: string; content: string }> = [
  { relative: 'SKILL.md', content: skillMd },
  { relative: 'references/work-items.md', content: skillWorkItems },
  { relative: 'references/pull-requests.md', content: skillPullRequests },
  { relative: 'references/automation.md', content: skillAutomation },
  { relative: 'references/pipelines.md', content: skillPipelines },
];

/**
 * Written whole rather than spliced into a marked block: unlike
 * AGENTS.md, this tree is dova's alone, so there is no surrounding
 * content of the user's to preserve.
 */
function writeSkill(fsLike: FileSystemLike, skillRoot: string, dryRun: boolean): BlockAction {
  let action: BlockAction = 'unchanged';
  for (const file of SKILL_FILES) {
    const absolute = path.join(skillRoot, ...file.relative.split('/'));
    if (fsLike.readFile(absolute) === file.content) continue;
    action = action === 'unchanged' ? (fsLike.readFile(absolute) === null ? 'created' : 'updated') : action;
    if (!dryRun) {
      fsLike.mkdirp(path.dirname(absolute));
      fsLike.writeFile(absolute, file.content);
    }
  }
  return action;
}

export type InstallScope = 'global' | 'repo';

export interface InstructionsInstallResult {
  scope: InstallScope;
  /** Repo root for a --repo install; the home directory for a global one. */
  root: string;
  files: Array<{ file: string; read_by: string; action: BlockAction }>;
  warnings: string[];
  dryRun: boolean;
}

/**
 * Copilot honours `.github/copilot-instructions.md` by default, but a
 * `.vscode/settings.json` inherited from a template repo (or an
 * enterprise policy file) can set `useInstructionFiles` to false — in
 * which case everything here is written correctly and silently ignored.
 * Cheap to check, and the alternative is a failure with no symptom.
 */
export function checkCopilotDisabled(fsLike: FileSystemLike, root: string): string | null {
  const settingsPath = path.join(root, '.vscode', 'settings.json');
  const raw = fsLike.readFile(settingsPath);
  if (raw === null) return null;
  // Deliberately a regex rather than JSON.parse: VS Code settings files
  // legitimately contain comments and trailing commas, which JSON.parse
  // rejects — and a parse failure here must not fail the install.
  if (/"github\.copilot\.chat\.codeGeneration\.useInstructionFiles"\s*:\s*false/.test(raw)) {
    return `.vscode/settings.json sets github.copilot.chat.codeGeneration.useInstructionFiles to false — Copilot will ignore .github/copilot-instructions.md until that is true.`;
  }
  return null;
}

function writeTarget(
  fsLike: FileSystemLike,
  absolute: string,
  block: string,
  preamble: string | undefined,
  dryRun: boolean
): BlockAction {
  const existing = fsLike.readFile(absolute);
  let { content, action } = applyBlock(existing, block);
  // A preamble (e.g. VS Code's `applyTo` frontmatter) is part of
  // creating the file, not of the block — on update it's already there,
  // sitting before the markers, and applyBlock preserves it.
  if (existing === null && preamble) content = preamble + content;
  if (!dryRun && action !== 'unchanged') {
    fsLike.mkdirp(path.dirname(absolute));
    fsLike.writeFile(absolute, content);
  }
  return action;
}

export function runInstructionsInstall(opts: {
  scope?: InstallScope;
  /** Repo root — required for a --repo install, ignored for a global one. */
  root?: string;
  home?: string;
  dryRun?: boolean;
  fs?: FileSystemLike;
  block?: string;
}): InstructionsInstallResult {
  const fsLike = opts.fs ?? nodeFs;
  const scope: InstallScope = opts.scope ?? 'global';
  const dryRun = Boolean(opts.dryRun);
  const files: InstructionsInstallResult['files'] = [];
  const warnings: string[] = [];

  if (scope === 'global') {
    const home = opts.home ?? os.homedir();
    const block = opts.block ?? instructionsBlock;
    for (const target of resolveGlobalTargets(fsLike, home)) {
      const action = writeTarget(fsLike, target.path, block, target.preamble, dryRun);
      files.push({ file: target.label, read_by: target.read_by, action });
    }
    files.push({
      file: '~/.agents/skills/dova/',
      read_by: 'Devin Desktop and Copilot, on demand',
      action: writeSkill(fsLike, path.join(home, '.agents', 'skills', 'dova'), dryRun),
    });
    return { scope, root: home, files, warnings, dryRun };
  }

  const root = opts.root;
  if (root === undefined) throw new UserError('A repo-scoped install needs a repo root.');
  const block = opts.block ?? instructionsBlock;

  for (const target of TARGETS) {
    const file = target.file === 'AGENTS.md' ? resolveAgentsFile(fsLike, root) : target.file;
    const action = writeTarget(fsLike, path.join(root, file), block, undefined, dryRun);
    files.push({ file, read_by: target.read_by, action });
  }

  files.push({
    file: '.agents/skills/dova/',
    read_by: 'Devin Desktop and Copilot, on demand',
    action: writeSkill(fsLike, path.join(root, '.agents', 'skills', 'dova'), dryRun),
  });

  const copilotWarning = checkCopilotDisabled(fsLike, root);
  if (copilotWarning) warnings.push(copilotWarning);

  return { scope, root, files, warnings, dryRun };
}
