import path from 'node:path';
import fs from 'node:fs';
import instructionsBlock from '../instructions/block.md';

/* ------------------------------------------------------------------ *
 * `dova instructions init` — writes dova's usage rules into the files
 * coding agents actually read.
 *
 * Named for what these files are (VS Code and GitHub both call them
 * "custom instructions") rather than "agents", which now means a custom
 * agent persona — an `.agent.md` role definition with its own tools and
 * model. This command writes neither of those.
 *
 * Two files, not one, because no single file is read by default by both
 * targets. Devin Desktop (what Windsurf became in June 2026; its Cascade
 * agent reached end-of-life that July, replaced by Devin Local) reads a
 * root AGENTS.md as an always-on rule, feeding it into the same rules
 * engine that backs .devin/rules/ — so there's no need to also write
 * .devin/rules/, and the legacy .windsurf/ directory is superseded.
 * VS Code's AGENTS.md support, by contrast, is experimental and off
 * behind `chat.useAgentsMdFile`; there `.github/copilot-instructions.md`
 * is what works out of the box. The same content goes in both,
 * generated from one source rather than maintained twice.
 *
 * Deliberately not a symlink: a Windows checkout with
 * core.symlinks=false turns one into a text file containing a path,
 * silently, and Azure DevOps shops skew Windows.
 * ------------------------------------------------------------------ */

export const BLOCK_START = '<!-- dova:start -->';
export const BLOCK_END = '<!-- dova:end -->';

const BLOCK_NOTE = `${BLOCK_START}\n<!-- Generated by \`dova instructions init\`. Edits inside this block are overwritten; edit outside it freely. -->`;

export interface InstructionsTarget {
  /** Repo-relative path. */
  file: string;
  /** Which agent reads it by default, for the summary line. */
  read_by: string;
}

export const TARGETS: InstructionsTarget[] = [
  { file: 'AGENTS.md', read_by: 'Devin Desktop / Windsurf (also Cursor, Codex)' },
  { file: path.join('.github', 'copilot-instructions.md'), read_by: 'GitHub Copilot in VS Code' },
];

/**
 * Devin Desktop accepts `agents.md` as well as `AGENTS.md`. On a
 * case-sensitive filesystem, writing the canonical spelling into a repo
 * that already uses the lowercase one would leave two rule files both
 * being read — so an existing variant wins over our preferred casing.
 */
export function resolveAgentsFile(fsLike: FileSystemLike, root: string): string {
  for (const variant of ['AGENTS.md', 'agents.md']) {
    if (fsLike.readFile(path.join(root, variant)) !== null) return variant;
  }
  return 'AGENTS.md';
}

export type BlockAction = 'created' | 'updated' | 'appended' | 'unchanged';

/**
 * Splices dova's block into a file's existing content: replacing it in
 * place if it's already there, appending if the file exists without it,
 * or standing alone in a new file. Everything outside the markers is
 * left exactly as it was — these files usually already say things about
 * the repo that have nothing to do with dova.
 */
export function applyBlock(existing: string | null, block: string): { content: string; action: BlockAction } {
  const wrapped = `${BLOCK_NOTE}\n\n${block.trim()}\n${BLOCK_END}\n`;

  if (existing === null) {
    return { content: wrapped, action: 'created' };
  }

  const start = existing.indexOf(BLOCK_START);
  const end = existing.indexOf(BLOCK_END);
  if (start !== -1 && end !== -1 && end > start) {
    const before = existing.slice(0, start);
    const after = existing.slice(end + BLOCK_END.length).replace(/^\n/, '');
    const content = `${before}${wrapped}${after}`;
    return { content, action: content === existing ? 'unchanged' : 'updated' };
  }

  const separator = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
  return { content: `${existing}${separator}${wrapped}`, action: 'appended' };
}

export interface FileSystemLike {
  readFile(file: string): string | null;
  writeFile(file: string, content: string): void;
  mkdirp(dir: string): void;
}

export const nodeFs: FileSystemLike = {
  readFile: (file) => {
    try {
      return fs.readFileSync(file, 'utf8');
    } catch {
      return null;
    }
  },
  writeFile: (file, content) => fs.writeFileSync(file, content, 'utf8'),
  mkdirp: (dir) => fs.mkdirSync(dir, { recursive: true }),
};

export interface InstructionsInstallResult {
  root: string;
  files: Array<{ file: string; read_by: string; action: BlockAction }>;
  warnings: string[];
  dryRun: boolean;
}

/**
 * Copilot honours `.github/copilot-instructions.md` by default, but a
 * `.vscode/settings.json` inherited from a template repo (or an
 * enterprise policy file) can set `useInstructionFiles` to false — in
 * which case everything here is written correctly and silently ignored.
 * Cheap to check, and the alternative is a failure with no symptom.
 */
export function checkCopilotDisabled(fsLike: FileSystemLike, root: string): string | null {
  const settingsPath = path.join(root, '.vscode', 'settings.json');
  const raw = fsLike.readFile(settingsPath);
  if (raw === null) return null;
  // Deliberately a regex rather than JSON.parse: VS Code settings files
  // legitimately contain comments and trailing commas, which JSON.parse
  // rejects — and a parse failure here must not fail the install.
  if (/"github\.copilot\.chat\.codeGeneration\.useInstructionFiles"\s*:\s*false/.test(raw)) {
    return `.vscode/settings.json sets github.copilot.chat.codeGeneration.useInstructionFiles to false — Copilot will ignore .github/copilot-instructions.md until that is true.`;
  }
  return null;
}

export function runInstructionsInstall(opts: {
  root: string;
  dryRun?: boolean;
  fs?: FileSystemLike;
  block?: string;
}): InstructionsInstallResult {
  const fsLike = opts.fs ?? nodeFs;
  const block = opts.block ?? instructionsBlock;
  const files: InstructionsInstallResult['files'] = [];

  for (const target of TARGETS) {
    const file = target.file === 'AGENTS.md' ? resolveAgentsFile(fsLike, opts.root) : target.file;
    const absolute = path.join(opts.root, file);
    const { content, action } = applyBlock(fsLike.readFile(absolute), block);
    if (!opts.dryRun && action !== 'unchanged') {
      fsLike.mkdirp(path.dirname(absolute));
      fsLike.writeFile(absolute, content);
    }
    files.push({ file, read_by: target.read_by, action });
  }

  const warnings: string[] = [];
  const copilotWarning = checkCopilotDisabled(fsLike, opts.root);
  if (copilotWarning) warnings.push(copilotWarning);

  return { root: opts.root, files, warnings, dryRun: Boolean(opts.dryRun) };
}
